name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install Ubuntu dependencies
        run: sudo apt install -y libevent-dev libssl-dev memcached

      - name: Run memcached
        run: /usr/bin/memcached -p 12345 -m 64m -d

      - name: Set up caching
        uses: Swatinem/rust-cache@v2

      - name: Install the stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check source code formatting
        run: rustup component add rustfmt && cargo fmt -- --check

      - name: Run static analysis (clippy)
        run: rustup component add clippy && cargo clippy

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

  coverage:
    needs:
      build

    runs-on: ubuntu-latest

    steps:
      - name: Set up the nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install memcached
        run: sudo apt install -y memcached

      - name: Set up caching
        uses: Swatinem/rust-cache@v2

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run memcached
        run: /usr/bin/memcached -p 12345 -m 64m -d

      - name: Generate code coverage
        run: cargo tarpaulin --run-types Tests --all-features --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
